# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: RootIsGod
author:
  name: iaingblack
  email: blog@rootisgod.com
description: >- # this means to ignore newlines until "baseurl:"
  Sysadmin Blog for Cloud and General Day to Day Stuff
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.rootisgod.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username: iaingblack

# Build settings
theme: minima
minima:
  skin: dark
plugins:
  - jekyll-feed
  - jekyll-sitemap
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
        layout: "post"
        permalink: /:year/:title/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
